Solution Zaitsev
Codefinity-py/lab_6 pull request #1
Opened 2023-10-28 10:42 UTC by DanyilZaitsev

2023-10-30 12:32 UTC, Codefinity-Java requested changes

2023-10-30 12:32 UTC, Codefinity-Java commented on main.py
> +        print(f"Acceleration for Car: {self.speed}")
Де у тебе прописана логіка підвищення швидкості в методі прискорення? 
Також тобі не потрібно перевизначати ці методи в класах наслідниках, достатньо використовувати батьківський клас.

2023-10-30 15:01 UTC, DanyilZaitsev commented
А що за логіка має бути? Метод прискорення бере задану швидкість та додає
до неї прискорення яке необхідно ввести параметром методу при його виклику.
Перевизначив методи у Дочірніх класах для наглядного прикладу.

пн, 30 окт. 2023 г. в 14:32, Codefinity-Java ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In main.py
> <https://github.com/Codefinity-py/lab_6/pull/1#discussion_r1376134276>:
>
> > +    def accelerate(self, add_speed):
> +        super().accelerate(add_speed)
> +        print(f"Acceleration for Car: {self.speed}")
>
> Де у тебе прописана логіка підвищення швидкості в методі прискорення?
> Також тобі не потрібно перевизначати ці методи в класах наслідниках,
> достатньо використовувати батьківський клас.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Codefinity-py/lab_6/pull/1#pullrequestreview-1704004777>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCU3IXLDRMRICLWLLVUVQ63YB6M4ZAVCNFSM6AAAAAA6UAAB56VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMBUGAYDINZXG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-30 15:02 UTC, DanyilZaitsev commented
Усі тести були пройдені.


пн, 30 окт. 2023 г. в 17:01, Danyil Zaitsev ***@***.***>:

> А що за логіка має бути? Метод прискорення бере задану швидкість та додає
> до неї прискорення яке необхідно ввести параметром методу при його виклику.
> Перевизначив методи у Дочірніх класах для наглядного прикладу.
>
> пн, 30 окт. 2023 г. в 14:32, Codefinity-Java ***@***.***>:
>
>> ***@***.**** requested changes on this pull request.
>> ------------------------------
>>
>> In main.py
>> <https://github.com/Codefinity-py/lab_6/pull/1#discussion_r1376134276>:
>>
>> > +    def accelerate(self, add_speed):
>> +        super().accelerate(add_speed)
>> +        print(f"Acceleration for Car: {self.speed}")
>>
>> Де у тебе прописана логіка підвищення швидкості в методі прискорення?
>> Також тобі не потрібно перевизначати ці методи в класах наслідниках,
>> достатньо використовувати батьківський клас.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Codefinity-py/lab_6/pull/1#pullrequestreview-1704004777>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BCU3IXLDRMRICLWLLVUVQ63YB6M4ZAVCNFSM6AAAAAA6UAAB56VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMBUGAYDINZXG4>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2023-11-01 11:35 UTC, Codefinity-Java approved these changes

2024-12-30 10:22 UTC, closed without merging